server:
  port: 8080



spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uberinterndemo
    username: root
    password: 287515GGgantic_


#开启日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# MQTT Configurations
ximo:
  mqtt:
    host: tcp://127.0.0.1:1883
    clientid: mqttId2
    username: admin
    password: public
    timeout: 1000
    keepalive: 10

alipay:
  appId: 9021000132613402
  appPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDV2AP38jA2zLJJmg+KRp9MoJKf/tfp7aOVotTom4EfqIqFZ1TErGu9MfZXoppuVngQzm79FONAHb+JKkPTRJ/dfRP94CSGQr/Ifc5vU5+fNkBFBPdxIW+G/cMCmeMlwR5cW7rQi1erk8BlfG1Rq1WoWbJSNOaehw5z0iXGmm30HDhMqwo8vHNUShye1YlJMVqq7J/yApQT2qTlaPIX0/8OyoVqVmry19Np1GP4MOLjUZx4woD4uKJhYg3wFYnIGyWr5doordmnDaisOvTuldzV56tqMxE3s9dfGOAMvkHQWAd9jp7sNvxBtTRMnITuoCcH9E3Z5EjxJ+exx9xMNLahAgMBAAECggEBALO59zPn6F/WUK4NfqwfyPkVJ8ay4HMqmEdGcJ0DPVYHSEzw2MzngTGlET78WcEMiaLObXflm02i8vzsec7RqW71Fd1VCj2RUjDGk777UHf2l7OqhfEeQeb51nGUNtXfZo4HRo7J3ihFaPmixxpR3w88O+Rds8pfBmWPpNIzrt/vYWxsxyZDz793fyAMCN263YOnY3LAc0/OsLdv2GyUgZcFO2QH+4ORZt9J+kYSB0NB3zU1uRJgu0ybfDhQCO6UgFsZVSvh5BIWUTaUUYX0wMzSmfDl4zzrlGjDeP6xILwCPzxN8je5Uj3ZNW+mj/b5R3XEVCIqtJx0i7gNQ6Bti7ECgYEA/IpGAgwBVpQ5asWu0MHm6UPs2e/p5kGugqIsYDK6yizhgSus5UR/cjnAD3oTVUO089K814i4e0rTWfWvJEkcTyLziM95wyW8ybWW+ehJRkwi2nIMhGrclVgZJABkCVSjsXv1aqUHhaMgWbRf6LGW84EK9kRsbiCWhA59Kp6GRDUCgYEA2MYGCPPPHH5LYhT2NpIQvssezkHYQJSKCvfALMJL+16Ox5FclOUh+ewHSmb6UBPKNqBIU8G1RTtFR4smxK/67ytsHTk2isgK9Xaj8WJNw9m+nNoznAIh2huZHn2NHspDvVhl57VvhwU5TVoJXdX9mm54YCWzdmjhs178DnPfXj0CgYEAqYXEcvFOIKlFVbg3nmjbMbDoGG/lKizjEUv9z+Gd48N26PfBivGNP8cmdv0yZyUZHidTnrdnZ1QWRigXFpuBRlom8qqbiPUXIqwkGcPlFCxdpRez8VuukQ3fanxcqqrHa4fTeXAoeXvEZpMfYpt7wh/YlPHfe5mikCkNuoNJjBUCgYEAyY7vA5n3hM3lt/A3sywDh/QD09KjigDTjjkpJjUPQ057whJmHEglXGXbrZGsw5JzHnHQbpiZvSLMWyaGyLG8yG/+mfmdvlMc5XoIHCTEnAu10dCN1kyhP1UT/abN9cgqTj+ImXc5mTkBO+ww82BK6zI2mWfUw4/n9Mmn4qRZGB0CgYBc1/PC8LG0CkFT3t+6/EJHYZdasD03O/acj8BB5Iycery6Z1Z7P/gcJx+dbFBAtBM2h2KKteg4w5aYsXTO2Oka3UI0tAGEySV8IQl4nGIrzX9Ew8l4MkKcu+wkuCBCvoP/TT14RKEDMe7Jt5UxPNhoB4KTQvUJTggVWUWkf+Kw+g==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAra+UsbGG2dd8lVigpgdplVVN3jqdSd2RnNx2Y3VL1nLwCSx4vBsqbRN0Zy2jiWvqtCCJ5IzB6lxkK9buOTmtGUJyNsHY9cJuPKL/QsDzPHPUIKMuN+w9hU4Fdm/X2p1bLju7IV6VoQId5X1pUZAiP5TS+s08tEOTTw3xQC0orvzYK7sReOqhMwCBCbjPE3RGaqyoZS6LCRzkm8Vv5idqOZ9b2Bn2TcxpVzKhaUNBA8JAxtfx7AnIpD4jND/L7FayqdA0taJNt4HwFENhDF0nrPXivtW9YWuUWfgwcpYXRqy8x4exQmHKHH2uDFhXqLaAea7zyhwiM0Wd5ArLx9uwBwIDAQAB
  notifyUrl: http://5eu3v9.natappfree.cc/alipay/notify
